esphome:
  project:
    name: Athom.7W Bulb E27 (LB01-7W-E27-TAS)
    version: "0.9"

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
  - platform: esp8266_pwm
    id: warm_white_output
    pin: GPIO13
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5


light:
  - platform: rgbww
    name: "${friendly_name}"
    red: red_output
    green: green_output
    blue: blue_output
    warm_white: warm_white_output
    cold_white: white_output
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
