debug:
  update_interval: 60s

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true

# --- Diagnostic Sensors (Disabled by Default) ---
  - platform: debug
    free:
      name: ${friendly_name} Free Heap Memory
      unit_of_measurement: bytes
      icon: mdi:memory
    # Hidden unless explicitly enabled in HA UI
      entity_category: "diagnostic"
      disabled_by_default: true

text_sensor:
  - platform: debug
    device:
      name: ${friendly_name} Device Info
      entity_category: "diagnostic"
      disabled_by_default: true
    reset_reason:
      name: ${friendly_name} Restart Reason
      entity_category: "diagnostic"
      disabled_by_default: true
    #Hidden unless explicitly enabled in HA UI

  - platform: wifi_info
    ip_address:
      name: "ESP IP Address"
      entity_category: "diagnostic"
      disabled_by_default: true

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: "diagnostic"
    
switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"
    entity_category: "diagnostic"
    icon: mdi:restart
    # Hidden unless explicitly enabled in HA UI
    disabled_by_default: true
         
# --- End Diagnostic Sensors ---
# Give the user a graphical control over the timeout
# See: https://esphome.io/components/number/template.html

