# In wifi.yaml
wifi:
  ssid: !secret trusted_ssid
  password: !secret trusted_password
  fast_connect: true
  power_save_mode: none
  min_auth_mode: WPA2
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-4Ch-Pro Fallback Hotspot"