substitutions:
  name: soundtown-amp #change
  friendly_name: Soundtown Amp #change
  icon: "mdi:light-switch"
  event: nodered_automation
  button: button
  board: esp01_1m

esphome:
  project:
    name: Sonoff.S31 Lite 
    version: "1.0"

packages:   # as a list
  - !include common/switch_base.yaml
  
api:

switch:
  - platform: gpio
    name: Relay
    pin: GPIO12
    id: relay
     # Resume last state on boot if possible. Else, off
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - homeassistant.service:
            service: logbook.log
            data:
              name: "Soundtown Amp"
              message: "HTTP Link: Trigger Received - Powering ON"
              entity_id: "switch.soundtown_amp_relay"
    on_turn_off:
      then:
        - homeassistant.service:
            service: logbook.log
            data:
              name: "Soundtown Amp"
              message: "HTTP Link: Trigger Received - Powering OFF"
              entity_id: "switch.soundtown_amp_relay"