substitutions:
  name: william-bedroom-lamp
  friendly_name: William Bedroom Lamp
  device_type: light
  board: esp8285

packages:   # as a list
  - !include common/wifi.yaml
  - !include common/bulb_base.yaml
  - !include common/athom_e27_7w_bulb.yaml